name: Run Supabase Script Every Hour

on:
  schedule:
    - cron: '0 * * * *'  # 毎時0分に実行
  workflow_dispatch:     # 手動実行も可能にする

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run the Python script
        env:
          RAKUTEN_APP_ID: ${{ secrets.RAKUTEN_APP_ID }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          ENV: ${{ vars.ENV }}
        run: |
          # 環境変数を確認
          echo "RAKUTEN_APP_ID: $RAKUTEN_APP_ID"
          echo "SUPABASE_URL: $SUPABASE_URL"
          echo "SUPABASE_KEY: $SUPABASE_KEY"
          echo "ENV: $ENV"
          # Pythonスクリプトを実行
          python main2.py
